WW-11: delete sighting endpoint
techswitch-learners/whale-spotting-2022-apr pull request #12
Opened 2022-07-01 10:02 UTC by Palak843

We have made a Delete Sighting endpoint.

2022-07-04 14:48 UTC, TimLeach635 requested changes
A few changes here!

2022-07-04 14:48 UTC, TimLeach635 commented on backend/Repositories/SightingRepo.cs
> +         public Sighting DeleteSighting(int id)
Line separating these two methods please!
```suggestion
        }
        
         public Sighting DeleteSighting(int id)
```

2022-07-04 14:48 UTC, TimLeach635 commented on backend/Repositories/SightingRepo.cs
> +         public Sighting DeleteSighting(int id)
I'm not sure how it happened but the methods are indented by one space more than the brackets!
```suggestion
        public Sighting GetById(int id)
        {
            return _context
                .Sightings
                .Single(s => s.Id == id);
        }
        public Sighting DeleteSighting(int id)
```

2022-07-04 14:48 UTC, TimLeach635 commented on backend/Repositories/SightingRepo.cs
> +         public Sighting DeleteSighting(int id)
You don't need to call it `DeleteSighting` - it's the Sightings Repo, we know what we're deleting! `DeleteById` is probably a better name (and is consistent with your other method, `GetById`)

2022-07-04 14:48 UTC, TimLeach635 commented on backend/Repositories/SightingRepo.cs
> +            return sighting;
You shouldn't return the deleted object, it's been deleted! From the point of view of the API, this Sighting should no longer exist!

2022-07-04 14:48 UTC, TimLeach635 commented on backend/Repositories/SightingRepo.cs
> +        Sighting DeleteSighting(int id);
As below, a deletion shouldn't return anything

2022-07-04 14:48 UTC, TimLeach635 commented on backend/Services/SightingService.cs
> +        public Sighting DeleteSighting(int id)
Deletions shouldn't return anything!

2022-07-04 14:48 UTC, TimLeach635 commented on backend/Services/SightingService.cs
> +        public Sighting DeleteSighting(int id)
Also, rename this to match the repo

2022-07-04 14:48 UTC, TimLeach635 commented on backend/Repositories/SightingRepo.cs
> +        }
Actually, why did you create this method and then not use it? If you're not using it, please delete it!

2022-07-05 09:33 UTC, Jordan-Renaud commented on backend/Repositories/SightingRepo.cs
> +                .Single(s => s.Id == id);
Do I need to include the species in this at all to update the IsDeleted property?

2022-07-05 09:50 UTC, TimLeach635 commented on backend/Repositories/SightingRepo.cs
> +                .Single(s => s.Id == id);
Very good point, no you don't!

2022-07-05 12:31 UTC, TimLeach635 approved these changes

2022-07-06 11:01 UTC, merged